id: template.cpg-on-ebmonfhir.netzwerk-universitaetsmedizin.de
canonical: https://www.netzwerk-universitaetsmedizin.de/fhir/cpg-on-ebmonfhir/example
name: CPG-on-EBMonFHIR template
title: CPG-on-EBMonFHIR template
status: draft
version: 0.0.1-snapshot
fhirVersion: 5.0.0
copyrightYear: 2023+
releaseLabel: ci-build
publisher:
  name: Example
  url: https://www.example.com

dependencies:
  de.netzwerk-universitaetsmedizin.ebm-cpg:
    version: 0.8.0-snapshot

pages:
  index.md:
    title: CPG-on-EBMonFHIR template
  downloads.xml:
  changelog.md:
    title: Change Log

menu:
  Home: index.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Change Log: changelog.html

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  active-tables: 'true' # Whether to generate active tables in the generated fragments (tables that will expand and contract).
  apply-contact: 'false' # if true, overwrite all canonical resource contact details with that found in the IG.
  apply-jurisdiction: 'false' # if true, overwrite all canonical resource jurisdiction details with that found in the IG.
  apply-publisher: 'false' # if true, overwrite all canonical resource publisher details with that found in the IG.
  apply-version: 'false' # if true, overwrite all canonical resource version details with that found in the IG.  Default = false
  show-inherited-invariants: 'false' # If true, render inherited constraints in the full details and invariants view. Default = true
  usage-stats-opt-out: 'true' # If true, usage stats (information about extensions, value sets, and invariants being used) is not sent to fhir.org (see e.g. http://clinfhir.com/igAnalysis.html).
  excludexml: 'false' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludejsn: 'false' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludettl: 'true' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludemap: 'true' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludeexample: 'true'
  extension-domain: # An external domain for which extensions are allowed to come (else they'll be flagged as invalid when validating).
  - https://www.netzwerk-universitaetsmedizin.de
  - https://simplifier.net
